import { useState, useEffect } from "react";
import { ChildPortrait } from "./ChildPortrait";

const FRAGMENTS_BY_AGE: { maxAge: number; lines: string[] }[] = [
  {
    maxAge: 5,
    lines: [
      "they learned a new word",
      "they fell down and got back up",
      "they asked what a cloud is",
      "they cried for no reason",
      "they laughed at something small",
      "they needed a hug",
      "they made something and showed you",
      "they weren't scared of the dark tonight",
      "they said a word wrong in a way you'll never forget",
      "they discovered their shadow",
      "they asked if you would always be there",
      "they ate something off the floor",
      "they named a stuffed animal very seriously",
      "they had a nightmare and forgot it by morning",
      "they learned what no means",
      "they tried to put their shoes on the wrong feet",
      "they asked where they came from",
      "they hid something they broke",
      "they called someone else mama",
      "they made up a song about nothing",
      "they wouldn't let go of your hand",
      "they saw an animal die for the first time",
      "they asked if you were going to die",
      "they fell asleep mid-sentence",
      "they learned that other kids have different rules",
      "they ran just to feel fast",
      "they decided bugs were interesting",
      "they cried when you left the room",
      "they put something in the toilet that shouldn't go there",
      "they refused to eat anything that touched anything else on the plate",
      "they screamed for twenty minutes and then fell asleep immediately",
      "they told a stranger something embarrassing about you",
      "they learned the word 'why' and used it as a weapon",
      "they ate sand, on purpose, after being told not to",
      "they cried because their banana broke",
      "they called your friend by the wrong name, very confidently, for months",
      "they got scared of something completely harmless and totally irrational",
      "they tried to whisper and failed completely",
      "they got stuck in a shirt and panicked",
      "they said 'I do it' and then couldn't, then said 'I do it' again",
      "they cried at a song you didn't expect",
      "they brought you a rock as a gift",
      "they sat very still watching something and you didn't interrupt",
      "they made a rule about something and enforced it seriously",
      "they laughed so hard they fell over",
      "they touched everything in a store you said not to touch",
      "they needed to be carried even though they were too big",
      "they sang something under their breath and stopped when they noticed you heard",
      "they had a meltdown that was really about something else",
      "they ran to you when they got hurt even if you were far away",
      "they broke something and stood next to it looking at you",
      "they decided their stuffed animal had feelings and treated it accordingly",
      "they made you read the same book so many times you memorized it",
      "they got very interested in a drain",
      "they tried to stay awake so they wouldn't miss anything",
      "they had a best friend for one afternoon",
      "they collected rocks that looked like regular rocks to everyone else",
      "they wanted to come with you everywhere, even the bathroom",
      "they grabbed your face to make you look at them",
      "they went quiet in a crowd and you felt them lean into you",
      "they didn't understand why the thing ended",
      "they wanted one more hug before bed, and then one more",
      "they fell asleep somewhere inconvenient and you didn't move them",
      "they did something funny and then did it again to see if you'd laugh again",
      "they had a very strong opinion about a color",
      "they said something true that you weren't expecting",
      "they waved at a stranger and the stranger waved back and it was everything",
      "they tried to help and made it significantly worse",
      "they bit into a lemon and kept going",
      "they got very attached to a spoon",
      "they fell asleep mid-chew",
      "they put on your shoes and tried to walk",
      "they pointed at something in the sky that wasn't there",
      "they decided one food was bad forever based on one experience",
      "they patted your arm when you seemed sad",
      "they announced a plan and immediately forgot what it was",
      "they asked you to stay just a little longer",
      "they asked why you can't see the wind",
      "they had a very serious conversation with a tree",
      "they wanted to know if clouds were hungry",
      "they made up a word and used it like they'd known it forever",
      "they insisted on carrying something too heavy for them and then cried when it was",
      "they told you they loved you and then immediately asked for a snack",
      "they had a very specific idea about how something should work and you weren't allowed to change it",
      "they cried because you didn't do the thing the way they imagined",
      "they asked why adults don't say what they mean",
      "they wanted to stay the same size forever",
      "they asked if you loved them more than anything and then tested it",
      "they had a very strong feeling about a sock seam",
      "they decided they were brave and then weren't sure",
      "they brought you a dead thing as a gift",
      "they asked what happens when people go away",
      "they held your hand like they were afraid you'd disappear",
      "they had a whole conversation with an imaginary friend and you overheard",
      "they wanted to know if dreams were real",
      "they made a fort and refused to leave it",
      "they asked why you have to be quiet in certain places",
      "they cried because something ended and the ending felt too sudden",
      "they wanted to be small again even though they were already small",
      "they asked what the word 'forever' really means",
      "they made you promise something very specific",
      "they didn't want to go to sleep because something might happen while they were asleep",
      "they asked if you were ever little",
      "they wanted to know what you were like when you were their age",
      "they told you a story that had only one character and it was them",
      "they decided something was unfair and were not willing to let it go",
      "they wanted to be carried even though they insisted they could walk",
      "they asked why people have to go to work",
      "they had a very strong opinion about someone they just met",
      "they asked what happens when toys break",
      "they wanted you to watch them do something over and over",
      "they had a strong reaction to the texture of something",
      "they asked why you can't have ice cream for breakfast",
      "they wanted to know if you'd always be there",
      "they made a very serious deal with you about something trivial",
      "they asked you to explain something and then explained it back better",
      "they wanted to know if animals dream",
      "they had a meltdown that turned out to be about something else entirely",
      "they asked why the moon follows us",
      "they insisted on doing something dangerous and then were scared of it",
      "they wanted to know where you go when you're not with them",
      "they told you they had a plan and you had no idea what it was",
      "they asked why people cry",
      "they wanted you to sit right next to them and not move",
      "they had a very specific way they wanted something done",
      "they asked if you could see them in the dark",
      "they wanted to know if you noticed when they weren't there",
      "they asked why some things are scary even when they're not real",
      "they made a rule that all food must be cut into exactly four pieces",
      "they cried because you used the wrong color plate and then couldn't explain why it mattered",
      "they brought you a half-eaten cookie as a gift and meant it with their whole heart",
      "they asked why the refrigerator light doesn't stay on when you close the door",
      "they wanted to know if trees get lonely when all their leaves fall off",
      "they had a very serious conversation with a pigeon for twenty minutes",
      "they decided that the number seven is blue and wouldn't accept any other explanation",
      "they asked you to draw them a dinosaur and critiqued your technique",
      "they wanted to know if you can taste colors or if that's just something people say",
      "they had a meltdown because their toast was the wrong shape and then ate it anyway",
      "they asked why you can't hear the ocean in a seashell if it's not actually the ocean",
      "they brought you a rock that looked exactly like every other rock but was special",
      "they wanted to know if your belly button used to be connected to their belly button",
      "they had a very strong opinion about whether socks should be wet or dry",
      "they asked why you can't have a pet cloud and were devastated by the answer",
      "they decided that wednesday is the worst day because it's not even close to the weekend",
      "they wanted to know if you remember what it felt like to be small",
      "they had a whole philosophy about why bubbles disappear and you weren't allowed to disagree",
      "they asked why you can't just keep your baby teeth forever in a special box",
      "they wanted to know if dogs dream about their favorite people",
      "they had a very specific idea about how the moon should behave at night",
      "they asked why your voice gets quiet when you're thinking about something sad",
      "they said 'i hate you' because you wouldn't let them eat dirt",
      "they picked their nose in public and showed you the booger",
      "they said 'i love grandma more than you' just to see your face",
      "they took off their diaper and ran around naked at grocery store",
      "they said 'you're not my real mom' when they didn't get their way",
      "they dug in their butt at the dinner table while guests were there",
      "they said 'i wish i had different parents' over breakfast",
      "they made papier-mâché out of toilet paper in the bathroom then proudly showed you",
      "they refused to wear clothes for three days straight",
      "they said 'you're stupid and i don't like you' after being told no",
      "they ate something clearly rotten and you found the wrapper",
      "they said 'nana lets me do whatever i want' like a tiny union organizer",
      "they peed on the floor right after you said 'do you need to go?'",
      "they said 'i don't love you anymore' and then wanted a hug five minutes later",
    ],
  },
  {
    maxAge: 10,
    lines: [
      "they made a new friend",
      "they lost something important",
      "they told a small lie",
      "they stayed up too late",
      "they had a hard day at school",
      "they asked a question you didn't know how to answer",
      "they figured something out on their own",
      "they decided they didn't like something anymore",
      "they got picked last",
      "they picked someone last",
      "they saw something on a screen they weren't supposed to",
      "they won something and felt strange about it",
      "they lost something and cried harder than you expected",
      "they got a best friend",
      "they lost a best friend",
      "they learned that some adults lie",
      "they had a phase you won't fully understand",
      "they read under the covers with a flashlight",
      "they kept a secret from you for the first time",
      "they wanted to be someone else for a while",
      "they felt left out and didn't say so",
      "they started caring what they looked like",
      "they got in trouble at school",
      "they stood up for someone smaller",
      "they tried to stay awake on a holiday and failed",
      "they asked what money is for",
      "they understood a joke that wasn't meant for them",
      "they learned what a real apology feels like",
      "they saw you cry and didn't know what to do",
      "they got brave about something small",
      "they told everyone at school something you said at home",
      "they lied badly and knew that you knew",
      "they got very into a hobby for exactly three weeks",
      "they convinced themselves they had a superpower",
      "they ate an entire box of something they weren't supposed to",
      "they cried over something so small you had to hide your smile",
      "they negotiated bedtime like a tiny lawyer",
      "they asked for a dog again, with new arguments",
      "they saw someone get hurt and didn't know what to feel",
      "they did something kind without being asked",
      "they tried to be cooler than they were",
      "they discovered that being smart could be embarrassing",
      "they got obsessed with a book you'd never read",
      "they asked why some kids have more than others",
      "they learned that you can miss someone who isn't gone yet",
      "they decided they were bad at something and stopped trying",
      "they did something mean and told you about it later",
      "they started caring about what was fair",
      "they learned their teacher was a person outside school and couldn't process it",
      "they cried at the end of something and didn't know why",
      "they made up a rule that everyone had to follow",
      "they found out a friend had a life at home they didn't know about",
      "they started noticing who had what",
      "they wanted to fix something that couldn't be fixed",
      "they got embarrassed about where you lived",
      "they hid how much they wanted to win",
      "they had a feeling they didn't have a word for yet",
      "they pretended not to care about something they cared about deeply",
      "they got very good at something quietly",
      "they went through a phase of telling the truth too much",
      "they started choosing their own clothes with strong opinions",
      "they had a nightmare that stayed with them",
      "they decided something was unfair and were right",
      "they started saying 'that's not fair' about things that were",
      "they wrote something private and hid it",
      "they noticed that their friends had problems at home too",
      "they wanted to ask something and decided not to",
      "they felt proud of something they couldn't explain",
      "they were excluded and pretended they didn't care",
      "they learned that some things can't be untaken back",
      "they tried to make someone feel better and it worked",
      "they figured out something adults assumed they didn't know",
      "they had a moment of quiet courage nobody saw",
      "they copied someone they admired, exactly",
      "they laughed when they weren't supposed to and couldn't stop",
      "they needed something and didn't know how to ask",
      "they got lost in a story for an entire afternoon",
      "they had a real conversation with you for the first time",
      "they said 'i hate school' every single morning for a month",
      "they wouldn't stop picking their scabs even after you said it ten times",
      "they said 'my friend's mom lets them stay up until 10pm' and then lied about it",
      "they made something disgusting with food and then acted surprised you were mad",
      "they said 'you never let me do anything fun' because you made them do homework",
      "they ate something they found on the floor at school and then lied about it",
      "they said 'i wish i could trade you for a better mom'",
      "they wouldn't wash behind their ears for weeks and it smelled",
      "they said 'everyone else gets to do it' when you said no",
      "they made a mess in the bathroom and didn't clean it up or tell you",
      "they said 'you're embarrassing me' in front of their friends",
      "they wouldn't brush their teeth no matter what you tried",
      "they said 'nana would never say no' like it was a tactical advantage",
      "they ate something gross and showed it to their friends like it was cool",
      "they said 'i don't love you anymore' after being told to clean their room",
      "they made a face whenever you spoke like everything you said was stupid",
      "they wouldn't shower even though they clearly smelled",
      "they said 'you're the worst parent ever' like a rehearsed line",
      "they picked their nose and then touched things when you weren't looking",
      "they said 'i hate living here' because you wouldn't buy them something",
      "they made something terrible in the kitchen and didn't clean it up",
      "they told you something at bedtime and then immediately fell asleep",
      "they asked why people have to die and then wouldn't talk about it",
      "they got excited about something and then pretended not to care",
      "they asked if you were proud of them and asked three times",
      "they had a very strong reaction to something that seemed small",
      "they asked for help and then insisted they could do it alone",
      "they started collecting something you didn't expect",
      "they had a moment where they understood something was complicated",
      "they asked why you don't talk about something",
      "they wanted to know if friends could be mad and still be friends",
      "they asked what your favorite memory of them was",
      "they had a whole inner life you didn't know about",
      "they started noticing when you were stressed and tried not to add to it",
      "they had a day where everything went wrong and handled it better than you expected",
      "they asked if they could trust you with something",
      "they decided to be brave about something that scared them",
      "they wanted to know what you were like at their age",
      "they had a moment where they felt sorry for someone else first",
      "they asked why some kids are mean and if there's anything you can do",
      "they had a conversation about fairness that lasted an hour",
      "they wanted to know if you'd still love them if they did something wrong",
      "they started noticing the world was bigger than they thought",
      "they had a moment where they felt grown up and it caught them off guard",
      "they asked why people say 'I'm fine' when they're not",
      "they wanted to know if you could remember being their age",
      "they had a very specific idea about what kind of person they wanted to be",
      "they asked why you have to grow up",
      "they had a moment where they realized you aren't perfect and decided that was okay",
      "they started keeping a journal and wouldn't let anyone see it",
      "they wanted to know what your job was really like",
      "they had a moment where they felt responsible for something",
      "they asked if you ever got in trouble when you were little",
      "they started noticing patterns in how people act",
      "they had a day where they felt like the main character",
      "they asked why some things are unfair and there's nothing you can do",
      "they wanted to know if you always knew what to do",
      "they had a moment where they felt proud of someone else",
      "they asked if people can change",
      "they wanted to know what kind of person you thought they were becoming",
      "they asked why you always check your phone first thing in the morning",
      "they decided that their bedroom should be painted a color you've never heard of",
      "they wanted to know if you remember the exact moment they stopped believing in the tooth fairy",
      "they had a very strong opinion about whether hot dogs are sandwiches and would argue about it for hours",
      "they asked why you can't just live in a treehouse forever and be done with school",
      "they wanted to know if you ever get embarrassed by them in public",
      "they had a whole system for organizing their toys that made perfect sense to them",
      "they asked why adults say 'in my day' like everything was so much simpler",
      "they wanted to know if you can get a refund on a bad haircut",
      "they decided that the cafeteria is the most political place in the school",
      "they asked why you can't have ice cream for dinner on tuesdays specifically",
      "they wanted to know if you remember what your worst tuesday was like",
      "they had a very specific idea about how to properly load the dishwasher",
      "they asked why you always sit in the same spot even when there are other empty chairs",
      "they wanted to know if you ever practiced being a grown up when you were little",
      "they decided that math is useless unless you're buying exactly seventeen watermelons",
      "they asked why your face does that thing when you're trying not to laugh",
      "they wanted to know if you can taste the difference between expensive and cheap pizza",
      "they had a whole theory about why the dryer eats socks and you were part of the conspiracy",
      "they asked why you can't just be friends with everyone and then realized that's impossible",
      "they wanted to know if you ever wanted to be a kid again when they're being difficult",
      "they decided that the middle seat on the couch is cursed and they have proof",
      "they asked why you always hum when you're cooking and you didn't even know you do that",
      "they wanted to know if you remember the exact moment you realized you were an adult",
      "they had a very strong opinion about whether cereal should be eaten before or after the milk",
      "they asked why you can't just quit being a parent if it's too hard sometimes",
      "they said 'you're fat' at the worst possible moment and everyone heard",
      "they wouldn't stop picking their nose even after you said it fourteen times",
      "they said 'i hate my life' because you made them do homework",
      "they showed their butt to their friends in the backyard and you had to intervene",
      "they said 'other parents don't care about this stuff' like a tiny philosopher",
      "they ate something off the floor that was clearly days old",
      "they said 'i wish i was adopted' for the third time this week",
      "they wouldn't wash their hands after the bathroom no matter what",
      "they said 'you ruined my life' because you wouldn't buy them something",
      "they made disgusting things in the bathtub and expected you to be impressed",
      "they said 'my friend's mom lets them do whatever they want'",
      "they peed in the shower and then denied it even though you could smell it",
      "they said 'you don't understand anything about me' at age seven",
      "they refused to wear deodorant even though they clearly needed it",
      "they said 'i'm never talking to you again' and then asked for a snack twenty minutes later",
    ],
  },
  {
    maxAge: 14,
    lines: [
      "they kept something from you",
      "they had a fight with a friend",
      "they started listening to new music",
      "they asked you not to embarrass them",
      "they cried and wouldn't say why",
      "they changed their mind about who they wanted to be",
      "they thought about what you said",
      "they started closing their door",
      "they said something cruel and felt terrible about it",
      "they wanted to be older than they were",
      "they discovered something that made them feel less alone",
      "they became someone's best friend",
      "they had a first crush they'd never admit to",
      "they started noticing how their body was different",
      "they said something funny that surprised you",
      "they stopped finding certain things funny",
      "they started to see you clearly, which hurt",
      "they spent a long time alone in their room",
      "they learned what unfairness really feels like",
      "they started worrying about the future",
      "they said they were fine when they weren't",
      "they became briefly obsessed with something you'll always remember",
      "they asked an impossible question and meant it",
      "they noticed something in the mirror they didn't like",
      "they apologized without being asked",
      "they read something that changed how they saw the world",
      "they texted a friend something they'd never say out loud",
      "they got hurt by someone they trusted",
      "they tried to hide how much they still needed you",
      "they stayed up thinking about the future",
      "they were briefly unbearable at dinner and didn't notice",
      "they discovered sarcasm and deployed it incorrectly",
      "they thought you were embarrassing without you doing anything",
      "they got very online about something for a while",
      "they explained something to you wrong, very confidently",
      "they had an enemy at school who was also their best friend",
      "they quit something you paid a lot of money for",
      "they asked you to knock before coming in",
      "they decided what kind of person they were, for now",
      "they started caring what strangers thought more than what you thought",
      "they had a belief they defended loudly that wasn't quite right",
      "they figured out that some adults are just winging it",
      "they wanted something they couldn't name",
      "they started performing a version of themselves in public",
      "they felt something they didn't tell anyone about",
      "they found a friend who got it in a way you didn't",
      "they wanted to matter to someone specific",
      "they decided something about themselves that stuck",
      "they started thinking about what things mean",
      "they were lonely in a new way they couldn't explain",
      "they discovered they could be someone different with different people",
      "they got let down by someone they'd idealized",
      "they started editing what they said before they said it",
      "they had an experience they couldn't tell you about yet",
      "they felt shame for the first time in a way that stayed",
      "they realized you weren't always right",
      "they started building an inner life they didn't share",
      "they had a feeling bigger than the words they had for it",
      "they made a choice about who they wanted to be seen as",
      "they stopped telling you everything and felt both free and lonely",
      "they had a moment where they understood something they wish they didn't",
      "they wanted desperately to be understood by one specific person",
      "they started having opinions about things that surprised you",
      "they discovered irony and found it useful",
      "they had a crush that reorganized their whole worldview",
      "they found out something about a friend's family they couldn't unlearn",
      "they started being protective of things they used to share freely",
      "they had a whole conversation with you in their head that they never had out loud",
      "they got really good at reading a room",
      "they felt the weight of something for the first time",
      "they started dreaming about the future in a real way",
      "they learned that loyalty is complicated",
      "they were braver in one moment than they'd ever been before",
      "they wanted to be known, not just liked",
      "they had a thought at 2am that they still think about",
      "they started noticing beauty in things that aren't beautiful",
      "they found music that felt like it was written for them specifically",
      "they had a day that was privately perfect",
      "they wanted to disappear for a weekend",
      "they started questioning the rules you set when they were little",
      "they had a moment where they felt sorry for you for the first time",
      "they asked if you ever felt like they do now",
      "they started noticing when adults are lonely and tried not to say it",
      "they had a whole philosophy about something they'd never talked to you about",
      "they wanted to be understood without having to explain",
      "they started seeing your mistakes as part of who you are",
      "they had a moment where they felt older than their age",
      "they asked what you'd do differently if you were their age",
      "they started caring about things you never taught them to care about",
      "they had a conversation with a friend that changed how they saw themselves",
      "they wanted to know if you still recognized them",
      "they started noticing how small the world felt sometimes",
      "they had a moment where they felt like they were becoming someone new",
      "they asked why being yourself can be so complicated",
      "they started understanding that people have reasons for doing things",
      "they had a thought about the future that scared them a little",
      "they wanted to know if it's okay to change your mind about who you are",
      "they started noticing how much they've changed in a year",
      "they had a moment where they felt grateful for something you do",
      "they asked if you ever felt like you were failing at being a parent",
      "they started caring about what kind of person they are, not just what they do",
      "they had a whole set of opinions about something you've never experienced",
      "they wanted to know if you see them as their own person now",
      "they started understanding that love can be complicated",
      "they had a moment where they felt responsible for how someone else felt",
      "they asked if you remember what it was like to be their age",
      "they started noticing how much they can handle",
      "they had a thought at 3am that they'll think about forever",
      "they wanted to know if you're okay with who they're becoming",
      "they started seeing that some things can't be fixed",
      "they had a moment where they felt like they were figuring it out",
      "they asked if it's normal to feel two opposite things at once",
      "they started caring about making good choices, not just the right ones",
      "they had a conversation with themselves that lasted all day",
      "they wanted to know if you think they're turning out okay",
      "they started understanding that everyone is just doing their best",
      "they had a moment where they felt proud of someone else's success",
      "they said 'i don't even love you anymore' just to see what you'd do",
      "they wouldn't shower for three days and smelled terrible but didn't care",
      "they said 'you embarrass me in front of my friends' every single week",
      "they said 'my friend's parents actually understand them' in a way that was meant to hurt",
      "they wouldn't stop picking their nose even at fourteen",
      "they said 'i wish i had never been born' because you said no to something",
      "they showed you something gross they found on the internet and laughed",
      "they said 'you have no idea what my life is like' and rolled their eyes",
      "they wouldn't wear deodorant even after you pointed out they smelled",
      "they said 'i'm going to run away' but didn't go anywhere",
      "they ate something disgusting in front of their friends and acted cool about it",
      "they said 'you're just like every other parent' like it was an insult",
      "they wouldn't wash their hands after using the bathroom anymore",
      "they said 'i don't need you' in a way that was clearly calculated to hurt",
      "they made something gross in the kitchen and left it there for days",
      "they said 'nana would never say no to this' and you knew it was true",
      "they wouldn't brush their teeth and their breath was terrible",
      "they said 'i hate you so much' and then asked for money the next day",
    ],
  },
  {
    maxAge: 18,
    lines: [
      "their voice changed and then they got self-conscious about it",
      "they fell for someone and immediately regretted it",
      "they started pulling away and said 'i just need space' in a way that hurt",
      "they came home late and had a perfectly reasonable excuse that you didn't believe",
      "they had a heartbreak and wouldn't talk about it but you could see it in everything they did",
      "they disagreed with everything you said and then agreed with you two days later",
      "they needed space and you had to pretend you weren't worried",
      "they were proud of something they didn't tell you about until you found out by accident",
      "they stayed out past curfew and had a reason that seemed solid but you knew better",
      "they drove alone for the first time and came home like nothing happened",
      "they made a decision you wouldn't have made and had to watch it play out",
      "they had a secret life that wasn't about you and there was evidence everywhere",
      "they got their heart broken and didn't come to you because they didn't think you'd get it",
      "they went somewhere without telling you and you found out from someone else",
      "they started questioning everything you told them and called you out on it",
      "they made a friend you've never met and they're weird and you said so",
      "they sat with a feeling instead of naming it and it came out as irritability",
      "they felt invisible in a crowd and didn't say anything about it at the time",
      "they made a mistake they won't talk about yet and the evidence is everywhere",
      "they stayed up all night for reasons you don't know and you pretended not to notice",
      "they held a job and quit it said it wasn't worth the stress",
      "they started thinking about who they want to be and got paralyzed by it",
      "they felt the future pressing in and panicked and then said 'never mind'",
      "they wondered if they were enough and then changed the subject when you started to answer",
      "they needed to hear something you didn't think to say and it showed",
      "they had a first time they'll always remember and won't tell you about it",
      "they let someone in they shouldn't have and you saw the exact moment it went wrong",
      "they were cruel and immediately regretted it but didn't apologize right away",
      "they made a promise they weren't sure they could keep and then tried anyway",
      "they looked at you differently and you noticed and it was deeply uncomfortable",
      "they were caught in a lie so elaborate you almost respected the effort",
      "they tried to negotiate everything and it was exhausting for both of you",
      "they ate everything in the house at midnight and blamed their siblings",
      "they slept until 2pm and felt this was reasonable and you were furious about it",
      "they gave you a one-word answer for three months straight and everyone suffered",
      "they were somehow both embarrassed by you and desperate for your approval at the same time",
      "they rolled their eyes so hard you're surprised they could see anything after that",
      "they discovered that you were human which annoyed them because it was inconvenient",
      "they started deciding what mattered and got very opinionated about everything",
      "they had a worldview they'd die on a hill for and you couldn't change their mind",
      "they felt something so big they had to put it somewhere and it came out as anger",
      "they built a wall and then stood behind it feeling alone but refusing to come out",
      "they started understanding why some things are sad and it was terrible timing",
      "they found something to believe in whether or not it was true and you had to live with it",
      "they had a night that defined the year and you found out three weeks later",
      "they started grieving something they didn't have a name for and it was hard to watch",
      "they realized they were becoming someone and it scared them",
      "they learned that some people won't stay and it made them colder",
      "they made a choice they haven't told you about and you can see the effects of it everywhere",
      "they decided who they were going to be at least for now and announced it dramatically",
      "they tried to hold two contradictory things at once and it didn't work out well",
      "they were braver than they thought they were and then immediately regressed",
      "they cared about something so much it embarrassed them and then they pretended they didn't",
      "they had a feeling they couldn't put down and it came out sideways in conversations",
      "they found out something about the world that couldn't be unfound and watched it change them",
      "they had a moment alone that mattered more than anything you planned and you weren't there for it",
      "they started building something internal that would take years to finish",
      "they had a version of themselves they only showed one person and it hurt you a little",
      "they did something they're still not sure how to feel about and you saw the aftermath",
      "they began to understand what it costs to be a person and got quiet about it",
      "they stopped believing something they'd believed their whole life and acted like they always knew",
      "they felt the weight of their own future for the first time and panicked about it",
      "they had an argument that changed how they thought and they didn't admit it at the time",
      "they loved someone who didn't love them back the same way and it was a whole thing",
      "they kept something secret not from shame but from tenderness and you understood but wished they'd told you",
      "they started choosing their own holidays and you had to learn to live with the changes",
      "they learned that time actually passes and it made them anxious and they didn't know why",
      "they had a phase where everything felt possible and then immediately after nothing did",
      "they made a friend who felt like a lifeline and then got hurt by them a month later",
      "they let someone down and couldn't fix it and blamed you for it somehow",
      "they did something brave that no one knew about and you found out years later",
      "they figured out something about themselves that explained a lot and took the fun out of everything",
      "they stayed when they could have left and you weren't sure if that was good or bad",
      "then they left when they could have stayed and you understood but it still hurt",
      "then they had a conversation that changed everything and you weren't invited to any of it",
      "they realized childhood was ending and felt both ways about it in the same hour",
      "they needed you and didn't reach for you because they were trying to prove something",
      "they started making plans that didn't include coming home",
      "they had a moment where they felt like they were running out of time",
      "they asked what you'd do if they never came back to this town",
      "they started seeing you as someone with your own story",
      "they had a whole set of regrets about something they wouldn't change",
      "they wanted to know if you think they made the right choices",
      "they started understanding that forgiveness is a practice",
      "they had a moment where they felt like they were finally growing up",
      "they asked if you ever thought about the person you were at their age",
      "they started noticing how much they've forgiven themselves",
      "they had a conversation with you that felt like talking to a peer",
      "they wanted to know if you're worried about them and then said they'll be okay",
      "they started seeing that love isn't always loud",
      "they had a moment where they felt proud of how far they've come",
      "they asked if it's okay to outgrow people",
      "they started understanding that some things are worth the risk",
      "they had a whole philosophy about what matters that you never taught them",
      "they wanted to know if you feel like time went too fast",
      "they started seeing that being alone isn't the same as being lonely",
      "they had a moment where they felt grateful for the hard things",
      "they asked if you think they turned out the way you hoped",
      "they started caring more about being kind than being right",
      "they had a conversation with their younger self and felt sorry for them",
      "they wanted to know if you remember the moment they became an adult",
      "they started understanding that you can love someone and still leave",
      "they had a moment where they felt like they were finally themselves",
      "they asked if it's okay to not have it all figured out yet",
      "they started seeing that their stories always include you",
      "they had a whole set of boundaries they learned the hard way",
      "they wanted to know if you're proud of the person they chose to become",
      "they started understanding that love is a choice they make every day",
      "they had a moment where they felt like they were ready for whatever comes next",
      "they asked if you ever think about them when they're not here",
      "they started using air quotes ironically even when no one was being ironic",
      "they wanted to know if you remember what it felt like to have a crush on someone you couldn't have",
      "they had a very strong opinion about whether pineapple belongs on pizza and you were part of the problem",
      "they asked why you always take the long way home when you're in a bad mood",
      "they wanted to know if you ever practiced conversations in the shower when you were their age",
      "they had a whole system for knowing when someone is lying and you failed at least three parts",
      "they decided that their generation is worse off financially than yours and had the receipts",
      "they asked why you can't just delete social media if it makes everyone miserable",
      "they wanted to know if you remember the exact moment you realized your parents were people",
      "they had a very specific idea about how to properly fold a fitted sheet and you were doing it wrong",
      "they asked why adults say 'when you have kids of your own' like that explains anything",
      "they wanted to know if you can taste the difference between tap water and bottled water when no one is looking",
      "they decided that group projects are just preparation for corporate life and they were not having it",
      "they asked why you always save the good candles for guests you don't even like that much",
      "they wanted to know if you ever wanted to change your name when you were their age",
      "they had a whole philosophy about why people text instead of calling and you were part of the decline of civilization",
      "they asked why you can't just admit when you don't know something without making up an answer",
      "they wanted to know if you remember what it felt like to think two weeks was a really long time",
      "they started writing in a journal and then immediately stopped because it felt weird",
      "they asked why you still have that one shirt even though it has a small stain you always apologize for",
      "they wanted to know if you ever had a friend group that just sort of ended and how you got over it",
      "they had a very strong opinion about whether it's okay to re-gift presents and you had no good answer",
      "they asked why you can't just be honest about how you feel instead of saying 'fine' when you're clearly not",
      "they wanted to know if you remember the exact moment you realized everything costs more than you thought",
      "they had a whole theory about why people post on social media when no one actually cares and you were uncomfortable",
      "they decided that adulthood is just doing things you don't want to do and then pretending you like them",
      "they asked why you always ask how they slept if you can't do anything about the answer",
      "they said 'i don't love you' just to see if you'd still love them anyway",
      "they wouldn't shower for four days and said 'it's not that bad'",
      "they said 'you were a terrible parent' and then asked for help with something",
      "they made something disgusting in the microwave and didn't clean it for weeks",
      "they said 'i wish i had been raised differently' in a way that was meant to wound",
      "they wouldn't wash their dishes even after you mentioned it five times",
      "they said 'my friend's parents actually support them' and you could tell it was calculated",
      "they ate something that smelled terrible and acted like it was fine",
      "they said 'you have no idea what real life is like' like they were the expert",
      "they wouldn't brush their teeth and their breath could knock someone out",
      "they said 'i'm going to be a better parent than you ever were'",
      "they made something gross in the kitchen and left it for you to find",
      "they said 'you ruined me in ways you'll never understand'",
      "they wouldn't do their laundry and had to wear the same shirt four days in a row",
      "they said 'i hate everything about this family' and then asked for money",
      "they showed you something disgusting on their phone and laughed when you were grossed out",
      "they said 'nana was right about everything' just to get under your skin",
      "they wouldn't clean their room even after you visited and it smelled",
    ],
  },
  {
    maxAge: Infinity,
    lines: [
      "they called less often",
      "they figured something out on their own",
      "they made a mistake and fixed it themselves",
      "they thought about what you taught them",
      "they stopped asking for your advice",
      "they understood something they couldn't have before",
      "they became someone",
      "they remembered",
      "they learned to be alone and were okay",
      "they paid a bill and felt strange about it",
      "they had a relationship that mattered",
      "they called to say nothing in particular",
      "they did something you always said they should do",
      "they did something you always said not to",
      "they said 'i'm too busy to talk' when you called",
      "they criticized your cooking at a family dinner",
      "they rolled their eyes when you told a story they'd heard before",
      "they said 'you don't understand modern life' in a condescending tone",
      "they complained about you to their friends",
      "they said 'stop being so annoying' when you tried to help",
      "they wouldn't call for weeks and then acted like nothing was wrong",
      "they said 'i know how to do this, mom' when you offered advice",
      "they made fun of your old photos",
      "they compared you unfavorably to their friend's parents",
      "they said 'you're embarrassing me' even as an adult",
      "they forgot your birthday and didn't apologize",
      "they said 'you always ruin everything' at a family gathering",
      "they wouldn't help when you were sick",
      "they said 'stop treating me like a child' when you were just concerned",
      "they posted something embarrassing about you online",
      "they said 'nobody asked for your opinion'",
      "they wouldnt pick up their kids when they promised",
      "they said 'youve always been jealous of me'",
      "they criticized your life choices to their spouse within earshot",
      "they said 'i wish youd just trust me' even though theyd broken your trust",
      "they wouldnt acknowledge everything youd done for them",
      "they said 'thats not how it happened' when you shared a memory",
      "they forgot to call on mothers day",
      "they said 'youre too controlling' when you tried to plan something",
      "they wouldnt apologize even when they knew they were wrong",
      "they said 'stop bringing up the past'",
      "they made a sarcastic comment about your appearance",
      "they wouldnt listen when you tried to explain your side",
      "they said 'you dont know anything about me' even though youd raised them",
      "they wouldnt acknowledge your sacrifices",
      "they said 'its not my fault you never had any friends'",
      "they wouldnt help you with technology even though it was simple",
      "they said 'you always make everything about you'",
      "they criticized your parenting to your face",
      "they said 'im done talking about this' and hung up",
      "they wouldnt acknowledge your achievements",
      "they said 'youre holding me back'",
      "they visited a place from their childhood and felt it differently",
      "they thought of you at a random moment",
      "they had to take care of something hard by themselves",
      "they made a home",
      "they told a story about their childhood you'd never heard",
      "they forgave something without saying so",
      "they understood why you were the way you were",
      "they missed you and didn't call",
      "they started becoming a little bit like you",
      "they worked through something in therapy you never knew about",
      "they held someone while they cried",
      "they hit a wall and kept going",
      "they chose something brave and quiet",
      "they said your name to a stranger with pride",
      "they sat with grief without asking anyone to fix it",
      "they grew into something you couldn't have predicted",
      "they called to ask how to boil an egg",
      "they finally admitted you were right about something",
      "they discovered they had your sense of humor and weren't sure how to feel",
      "they called because they missed you but talked about something else",
      "they texted 'are you awake' at an unreasonable hour",
      "they told a friend something you said, as wisdom, not knowing you were guessing",
      "they started giving other people the advice you gave them",
      "they accidentally became responsible",
      "they had a hard year and didn't tell you until it was over",
      "they learned something the hard way that you tried to warn them about",
      "they made a life that surprised you",
      "they found out what they were made of",
      "they carried something from childhood they didn't know they were carrying",
      "they got good at something you never knew they were working on",
      "they started to understand what childhood felt like from the inside",
      "they found the words for something they felt at twelve",
      "they realized what they'd been looking for",
      "they built something real",
      "they had a moment of clarity about who they are",
      "they finally stopped waiting for something to begin",
      "they became the kind of person who shows up",
      "they loved someone in a way that cost them something",
      "they looked back and saw it differently",
      "they forgave you for something without telling you",
      "they realized the thing they blamed you for was more complicated",
      "they kept a habit you didn't know you gave them",
      "they became someone you'd have liked to know",
      "they chose the harder right thing",
      "they stopped explaining themselves to people who didn't deserve it",
      "they built a life that asked a lot of them",
      "they had a moment of genuine peace",
      "they became someone's safe person",
      "they did something you always hoped they would",
      "they called on a day that wasn't a holiday just to hear your voice",
      "they passed on something you gave them without knowing where it came from",
      "they started telling their own childhood stories",
      "they let themselves be helped",
      "they got through something alone and it was enough",
      "they made a choice you would have made",
      "they made a choice you wouldn't have, and it worked",
      "they learned to ask for what they need",
      "they sat with someone else's grief and didn't try to fix it",
      "they understood something about you they couldn't have before",
      "they started to understand why you were the way you were, and forgave it",
      "they had a dream about their childhood",
      "they realized they were okay",
      "they became someone's parent and understood everything differently",
      "they thought of something you said, at exactly the right moment",
      "they started seeing their whole life from a distance",
      "they had a moment where they felt like they finally understood you",
      "they asked if you remember a specific small thing they did when they were little",
      "they started carrying something forward that you gave them",
      "they had a realization about who they are and it surprised them",
      "they wanted to know if you felt lonely when they left home",
      "they started understanding that you were their first home",
      "they had a moment where they felt grateful for everything",
      "they asked if you think about them when you're working on small things",
      "they started seeing that they are part of a story bigger than their own",
      "they had a whole set of things they wanted to say but hadn't figured out how",
      "they wanted to know if you're still becoming someone too",
      "they started understanding that love is patient even with yourself",
      "they had a moment where they felt like they were finally enough",
      "they asked if it's okay to not know what you're doing and mean it",
      "they started seeing that their childhood was a gift even with all its imperfections",
      "they had a conversation where they finally said what they meant",
      "they wanted to know if you feel like they turned out okay",
      "they started understanding that you can be proud and tired at the same time",
      "they had a moment where they felt like they were exactly where they needed to be",
      "they asked if you think they made you proud and then said it out loud first",
      "they started carrying something forward that you never taught them directly",
      "they had a whole set of things they wanted you to know",
      "they wanted to know if you remember who they were before they became who they are",
      "they started understanding that some things take a lifetime",
      "they had a moment where they felt like they were finally home",
      "they asked if it's okay to still need you sometimes",
      "they started seeing that you were always figuring it out too",
      "they had a realization about love that they wanted to share with you",
      "they wanted to know if you think about the person you've become because of them",
      "they started understanding that the story isn't over",
      "they had a moment where they felt like they were exactly who they were meant to be",
      "they asked if you remember the small moments and then told you one",
      "they started seeing that they are still becoming",
      "they had a whole set of things they wanted to do differently and were okay with that",
      "they wanted to know if you feel like the years went fast for you too",
      "they started understanding that love is the thing that outlasts everything else",
      "they asked why you still have their old drawings taped to the inside of a cabinet door",
      "they wanted to know if you remember the exact moment they stopped asking for a nightlight",
      "they had a very strong opinion about whether it's okay to eat cereal for dinner when no one is watching",
      "they asked why you always save the good cheese for people who don't even appreciate it",
      "they wanted to know if you ever practiced being a parent when you were little and what you got wrong",
      "they decided that you have too many tupperware containers and no clear system",
      "they asked why you can't just admit when you don't know the name of that actor even though it's on the tip of your tongue",
      "they wanted to know if you remember what it felt like to think a dollar was a lot of money",
      "they had a whole theory about why people take pictures of their food instead of eating it and you were uncomfortable",
      "they asked why you still buy the expensive paper towels even though you complain about money sometimes",
      "they wanted to know if you ever wanted to be famous when you were their age or if you just gave up quietly",
      "they decided that you have a very specific way of loading the dishwasher and they were going to do it differently no matter what",
      "they asked why you can't just delete an app if it makes you miserable instead of complaining about it every day",
      "they wanted to know if you remember the exact moment you realized you were becoming your own parents",
      "they started telling their friends that you used to say weird things and then realized you still do",
      "they had a whole philosophy about why people write lists when no one actually follows them and you were evidence",
      "they asked why you always save the good snacks for when company comes even though it's just them",
      "they wanted to know if you ever had a friend who moved away and how you got over not checking your mailbox every day",
      "they decided that you have too many decorative pillows and nowhere to actually sit",
      "they asked why you can't just admit when you're lost instead of driving in circles for twenty minutes",
      "they wanted to know if you remember what it felt like to think summer vacation was going to last forever",
      "they decided that you have a very specific way of folding towels and they were going to unfold them and do it better",
      "they started noticing that you still save restaurant menus you'll never use again",
      "they wanted to know if you ever wanted to learn an instrument and then just didn't and how you feel about that now",
      "they decided that you have too many plastic bags inside other plastic bags and no clear endgame",
      "they asked why you always ask how school was when you already know the answer is 'fine'",
      "they wanted to know if you remember what it felt like to think being twenty was old",
      "they started understanding that you're just making it up as you go too and that was somehow comforting",
      "they had a moment where they realized you never actually liked that band you played when they were growing up",
      "they said 'i don't love you' over the phone and you didn't know what to say",
      "they wouldn't call for months and then acted like nothing was wrong",
      "they said 'you were too strict' for the fourth time this month",
      "they made a comment about your cooking at a family dinner in front of everyone",
      "they said 'i hate how you always do that' in a way that sounded like they meant it",
      "they criticized your life choices at Thanksgiving and then asked for dessert",
      "they said 'you never supported me' when you absolutely did",
      "they wouldn't stop picking their nose even as an adult and it still grossed you out",
      "they made a passive-aggressive comment about your parenting style in front of the grandkids",
      "they said 'i'm nothing like you' like it was a good thing",
      "they forgot your birthday and then made excuses about being busy",
      "they said 'you worry too much' in a way that was clearly an insult",
      "they criticized how you raise the grandchildren to your face",
      "they said 'i wish you were more like Jake's mom' and you didn't know what to say",
      "they made a joke about your appearance and laughed when you were hurt",
    ],
  },
];

function sampleFragments(age: number, count = 4): string[] {
  const pool =
    FRAGMENTS_BY_AGE.find((b) => age <= b.maxAge)?.lines ??
    FRAGMENTS_BY_AGE[FRAGMENTS_BY_AGE.length - 1].lines;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

interface Props {
  childName: string;
  age?: number;
  gameId?: string | null;
  /** Live-streamed text from the LLM — shown over the fragment while generating. */
  streamingText?: string;
}

export function ProcessingScreen({ childName, age = 6, gameId, streamingText }: Props) {
  const [fragments] = useState(() => sampleFragments(age, 8));
  const [fragmentIdx, setFragmentIdx] = useState(0);

  useEffect(() => {
    setFragmentIdx(0);
    const id = setInterval(() => {
      // Advance once per slot; stop at the last — never repeat
      setFragmentIdx((i) => (i < fragments.length - 1 ? i + 1 : i));
    }, 10000);
    return () => clearInterval(id);
  }, [fragments.length]);

  return (
    <div className="processing-screen">
      <div className="processing-figure">
        <ChildPortrait age={age} size={140} gameId={gameId} />
      </div>
      <p className="processing-name">{childName}</p>
      <div className="processing-fragment-area">
        {streamingText ? (
          <div className="processing-stream-text">{streamingText}</div>
        ) : (
          <span key={fragmentIdx} className="processing-fragment-text">
            {fragments[fragmentIdx]}
          </span>
        )}
      </div>
    </div>
  );
}
