import { useState, useEffect } from "react";
import { ChildPortrait } from "./ChildPortrait";

const FRAGMENTS_BY_AGE: { maxAge: number; lines: string[] }[] = [
  {
    maxAge: 5,
    lines: [
      "they learned a new word",
      "they fell down and got back up",
      "they asked what a cloud is",
      "they cried for no reason",
      "they laughed at something small",
      "they needed a hug",
      "they made something and showed you",
      "they weren't scared of the dark tonight",
      "they said a word wrong in a way you'll never forget",
      "they discovered their shadow",
      "they asked if you would always be there",
      "they ate something off the floor",
      "they named a stuffed animal very seriously",
      "they had a nightmare and forgot it by morning",
      "they learned what no means",
      "they tried to put their shoes on the wrong feet",
      "they asked where they came from",
      "they hid something they broke",
      "they called someone else mama",
      "they made up a song about nothing",
      "they wouldn't let go of your hand",
      "they saw an animal die for the first time",
      "they asked if you were going to die",
      "they fell asleep mid-sentence",
      "they learned that other kids have different rules",
      "they ran just to feel fast",
      "they decided bugs were interesting",
      "they cried when you left the room",
      "they put something in the toilet that shouldn't go there",
      "they refused to eat anything that touched anything else on the plate",
      "they screamed for twenty minutes and then fell asleep immediately",
      "they told a stranger something embarrassing about you",
      "they learned the word 'why' and used it as a weapon",
      "they ate sand, on purpose, after being told not to",
      "they cried because their banana broke",
      "they called your friend by the wrong name, very confidently, for months",
      "they got scared of something completely harmless and totally irrational",
      "they tried to whisper and failed completely",
      "they got stuck in a shirt and panicked",
      "they said 'I do it' and then couldn't, then said 'I do it' again",
      "they cried at a song you didn't expect",
      "they brought you a rock as a gift",
      "they sat very still watching something and you didn't interrupt",
      "they made a rule about something and enforced it seriously",
      "they laughed so hard they fell over",
      "they touched everything in a store you said not to touch",
      "they needed to be carried even though they were too big",
      "they sang something under their breath and stopped when they noticed you heard",
      "they had a meltdown that was really about something else",
      "they ran to you when they got hurt even if you were far away",
      "they broke something and stood next to it looking at you",
      "they decided their stuffed animal had feelings and treated it accordingly",
      "they made you read the same book so many times you memorized it",
      "they got very interested in a drain",
      "they tried to stay awake so they wouldn't miss anything",
      "they had a best friend for one afternoon",
      "they collected rocks that looked like regular rocks to everyone else",
      "they wanted to come with you everywhere, even the bathroom",
      "they grabbed your face to make you look at them",
      "they went quiet in a crowd and you felt them lean into you",
      "they didn't understand why the thing ended",
      "they wanted one more hug before bed, and then one more",
      "they fell asleep somewhere inconvenient and you didn't move them",
      "they did something funny and then did it again to see if you'd laugh again",
      "they had a very strong opinion about a color",
      "they said something true that you weren't expecting",
      "they waved at a stranger and the stranger waved back and it was everything",
      "they tried to help and made it significantly worse",
      "they bit into a lemon and kept going",
      "they got very attached to a spoon",
      "they fell asleep mid-chew",
      "they put on your shoes and tried to walk",
      "they pointed at something in the sky that wasn't there",
      "they decided one food was bad forever based on one experience",
      "they patted your arm when you seemed sad",
      "they announced a plan and immediately forgot what it was",
      "they asked you to stay just a little longer",
    ],
  },
  {
    maxAge: 10,
    lines: [
      "they made a new friend",
      "they lost something important",
      "they told a small lie",
      "they stayed up too late",
      "they had a hard day at school",
      "they asked a question you didn't know how to answer",
      "they figured something out on their own",
      "they decided they didn't like something anymore",
      "they got picked last",
      "they picked someone last",
      "they saw something on a screen they weren't supposed to",
      "they won something and felt strange about it",
      "they lost something and cried harder than you expected",
      "they got a best friend",
      "they lost a best friend",
      "they learned that some adults lie",
      "they had a phase you won't fully understand",
      "they read under the covers with a flashlight",
      "they kept a secret from you for the first time",
      "they wanted to be someone else for a while",
      "they felt left out and didn't say so",
      "they started caring what they looked like",
      "they got in trouble at school",
      "they stood up for someone smaller",
      "they tried to stay awake on a holiday and failed",
      "they asked what money is for",
      "they understood a joke that wasn't meant for them",
      "they learned what a real apology feels like",
      "they saw you cry and didn't know what to do",
      "they got brave about something small",
      "they told everyone at school something you said at home",
      "they lied badly and knew that you knew",
      "they got very into a hobby for exactly three weeks",
      "they convinced themselves they had a superpower",
      "they ate an entire box of something they weren't supposed to",
      "they cried over something so small you had to hide your smile",
      "they negotiated bedtime like a tiny lawyer",
      "they asked for a dog again, with new arguments",
      "they saw someone get hurt and didn't know what to feel",
      "they did something kind without being asked",
      "they tried to be cooler than they were",
      "they discovered that being smart could be embarrassing",
      "they got obsessed with a book you'd never read",
      "they asked why some kids have more than others",
      "they learned that you can miss someone who isn't gone yet",
      "they decided they were bad at something and stopped trying",
      "they did something mean and told you about it later",
      "they started caring about what was fair",
      "they learned their teacher was a person outside school and couldn't process it",
      "they cried at the end of something and didn't know why",
      "they made up a rule that everyone had to follow",
      "they found out a friend had a life at home they didn't know about",
      "they started noticing who had what",
      "they wanted to fix something that couldn't be fixed",
      "they got embarrassed about where you lived",
      "they hid how much they wanted to win",
      "they had a feeling they didn't have a word for yet",
      "they pretended not to care about something they cared about deeply",
      "they got very good at something quietly",
      "they went through a phase of telling the truth too much",
      "they started choosing their own clothes with strong opinions",
      "they had a nightmare that stayed with them",
      "they decided something was unfair and were right",
      "they started saying 'that's not fair' about things that were",
      "they wrote something private and hid it",
      "they noticed that their friends had problems at home too",
      "they wanted to ask something and decided not to",
      "they felt proud of something they couldn't explain",
      "they were excluded and pretended they didn't care",
      "they learned that some things can't be untaken back",
      "they tried to make someone feel better and it worked",
      "they figured out something adults assumed they didn't know",
      "they had a moment of quiet courage nobody saw",
      "they copied someone they admired, exactly",
      "they laughed when they weren't supposed to and couldn't stop",
      "they needed something and didn't know how to ask",
      "they got lost in a story for an entire afternoon",
      "they had a real conversation with you for the first time",
    ],
  },
  {
    maxAge: 14,
    lines: [
      "they kept something from you",
      "they had a fight with a friend",
      "they started listening to new music",
      "they asked you not to embarrass them",
      "they cried and wouldn't say why",
      "they changed their mind about who they wanted to be",
      "they thought about what you said",
      "they started closing their door",
      "they said something cruel and felt terrible about it",
      "they wanted to be older than they were",
      "they discovered something that made them feel less alone",
      "they became someone's best friend",
      "they had a first crush they'd never admit to",
      "they started noticing how their body was different",
      "they said something funny that surprised you",
      "they stopped finding certain things funny",
      "they started to see you clearly, which hurt",
      "they spent a long time alone in their room",
      "they learned what unfairness really feels like",
      "they started worrying about the future",
      "they said they were fine when they weren't",
      "they became briefly obsessed with something you'll always remember",
      "they asked an impossible question and meant it",
      "they noticed something in the mirror they didn't like",
      "they apologized without being asked",
      "they read something that changed how they saw the world",
      "they texted a friend something they'd never say out loud",
      "they got hurt by someone they trusted",
      "they tried to hide how much they still needed you",
      "they stayed up thinking about the future",
      "they were briefly unbearable at dinner and didn't notice",
      "they discovered sarcasm and deployed it incorrectly",
      "they thought you were embarrassing without you doing anything",
      "they got very online about something for a while",
      "they explained something to you wrong, very confidently",
      "they had an enemy at school who was also their best friend",
      "they quit something you paid a lot of money for",
      "they asked you to knock before coming in",
      "they decided what kind of person they were, for now",
      "they started caring what strangers thought more than what you thought",
      "they had a belief they defended loudly that wasn't quite right",
      "they figured out that some adults are just winging it",
      "they wanted something they couldn't name",
      "they started performing a version of themselves in public",
      "they felt something they didn't tell anyone about",
      "they found a friend who got it in a way you didn't",
      "they wanted to matter to someone specific",
      "they decided something about themselves that stuck",
      "they started thinking about what things mean",
      "they were lonely in a new way they couldn't explain",
      "they discovered they could be someone different with different people",
      "they got let down by someone they'd idealized",
      "they started editing what they said before they said it",
      "they had an experience they couldn't tell you about yet",
      "they felt shame for the first time in a way that stayed",
      "they realized you weren't always right",
      "they started building an inner life they didn't share",
      "they had a feeling bigger than the words they had for it",
      "they made a choice about who they wanted to be seen as",
      "they stopped telling you everything and felt both free and lonely",
      "they had a moment where they understood something they wish they didn't",
      "they wanted desperately to be understood by one specific person",
      "they started having opinions about things that surprised you",
      "they discovered irony and found it useful",
      "they had a crush that reorganized their whole worldview",
      "they found out something about a friend's family they couldn't unlearn",
      "they started being protective of things they used to share freely",
      "they had a whole conversation with you in their head that they never had out loud",
      "they got really good at reading a room",
      "they felt the weight of something for the first time",
      "they started dreaming about the future in a real way",
      "they learned that loyalty is complicated",
      "they were braver in one moment than they'd ever been before",
      "they wanted to be known, not just liked",
      "they had a thought at 2am that they still think about",
      "they started noticing beauty in things that aren't beautiful",
      "they found music that felt like it was written for them specifically",
      "they had a day that was privately perfect",
    ],
  },
  {
    maxAge: 18,
    lines: [
      "their voice changed",
      "they fell for someone",
      "they started pulling away",
      "they came home late",
      "they had a heartbreak",
      "they disagreed with everything you said",
      "they needed space",
      "they were proud of something they didn't tell you about",
      "they stayed out past curfew and had a reason",
      "they drove alone for the first time",
      "they made a decision you wouldn't have made",
      "they had a secret life that wasn't about you",
      "they got their heart broken and didn't come to you",
      "they went somewhere without telling you",
      "they started questioning things you told them",
      "they made a friend you've never met",
      "they sat with a feeling instead of naming it",
      "they felt invisible in a crowd",
      "they made a mistake they won't talk about yet",
      "they stayed up all night for reasons you don't know",
      "they held a job and quit it",
      "they started thinking about who they want to be",
      "they felt the future pressing in",
      "they wondered if they were enough",
      "they needed to hear something you didn't think to say",
      "they had a first time they'll always remember",
      "they let someone in they shouldn't have",
      "they were cruel and immediately regretted it",
      "they made a promise they weren't sure they could keep",
      "they looked at you differently and you noticed",
      "they were caught in a lie so elaborate you almost respected it",
      "they tried to negotiate everything",
      "they ate everything in the house at midnight",
      "they slept until 2pm and felt this was reasonable",
      "they gave you a one-word answer for three months straight",
      "they were somehow both embarrassed by you and desperate for your approval",
      "they rolled their eyes so hard you're surprised they could see",
      "they discovered that you were human, which annoyed them",
      "they started deciding what mattered",
      "they had a worldview they'd die on a hill for",
      "they felt something so big they had to put it somewhere",
      "they built a wall and then stood behind it feeling alone",
      "they started understanding why some things are sad",
      "they found something to believe in, whether or not it was true",
      "they had a night that defined the year",
      "they started grieving something they didn't have a name for",
      "they realized they were becoming someone",
      "they learned that some people won't stay",
      "they made a choice they haven't told you about",
      "they decided who they were going to be, at least for now",
      "they tried to hold two contradictory things at once and couldn't",
      "they were braver than they thought they were",
      "they cared about something so much it embarrassed them",
      "they had a feeling they couldn't put down",
      "they found out something about the world that couldn't be unfound",
      "they had a moment alone that mattered more than anything you planned",
      "they started building something internal that would take years",
      "they had a version of themselves they only showed one person",
      "they did something they're still not sure how to feel about",
      "they began to understand what it costs to be a person",
      "they stopped believing something they'd believed their whole life",
      "they felt the weight of their own future for the first time",
      "they had an argument that changed how they thought",
      "they loved someone who didn't love them back the same way",
      "they kept something secret not from shame but from tenderness",
      "they started choosing their own holidays",
      "they learned that time actually passes",
      "they had a phase where everything felt possible",
      "they had a phase where nothing felt possible",
      "they made a friend who felt like a lifeline",
      "they let someone down and couldn't fix it",
      "they did something brave that no one knew about",
      "they figured out something about themselves that explained a lot",
      "they stayed when they could have left",
      "they left when they could have stayed",
      "they had a conversation that changed everything",
      "they realized childhood was ending and felt both ways about it",
      "they needed you and didn't reach for you",
    ],
  },
  {
    maxAge: Infinity,
    lines: [
      "they called less often",
      "they figured something out on their own",
      "they made a mistake and fixed it themselves",
      "they thought about what you taught them",
      "they stopped asking for your advice",
      "they understood something they couldn't have before",
      "they became someone",
      "they remembered",
      "they learned to be alone and were okay",
      "they paid a bill and felt strange about it",
      "they had a relationship that mattered",
      "they called to say nothing in particular",
      "they did something you always said they should do",
      "they did something you always said not to",
      "they visited a place from their childhood and felt it differently",
      "they thought of you at a random moment",
      "they had to take care of something hard by themselves",
      "they made a home",
      "they told a story about their childhood you'd never heard",
      "they forgave something without saying so",
      "they understood why you were the way you were",
      "they missed you and didn't call",
      "they started becoming a little bit like you",
      "they worked through something in therapy you never knew about",
      "they held someone while they cried",
      "they hit a wall and kept going",
      "they chose something brave and quiet",
      "they said your name to a stranger with pride",
      "they sat with grief without asking anyone to fix it",
      "they grew into something you couldn't have predicted",
      "they called to ask how to boil an egg",
      "they finally admitted you were right about something",
      "they discovered they had your sense of humor and weren't sure how to feel",
      "they called because they missed you but talked about something else",
      "they texted 'are you awake' at an unreasonable hour",
      "they told a friend something you said, as wisdom, not knowing you were guessing",
      "they started giving other people the advice you gave them",
      "they accidentally became responsible",
      "they had a hard year and didn't tell you until it was over",
      "they learned something the hard way that you tried to warn them about",
      "they made a life that surprised you",
      "they found out what they were made of",
      "they carried something from childhood they didn't know they were carrying",
      "they got good at something you never knew they were working on",
      "they started to understand what childhood felt like from the inside",
      "they found the words for something they felt at twelve",
      "they realized what they'd been looking for",
      "they built something real",
      "they had a moment of clarity about who they are",
      "they finally stopped waiting for something to begin",
      "they became the kind of person who shows up",
      "they loved someone in a way that cost them something",
      "they looked back and saw it differently",
      "they forgave you for something without telling you",
      "they realized the thing they blamed you for was more complicated",
      "they kept a habit you didn't know you gave them",
      "they became someone you'd have liked to know",
      "they chose the harder right thing",
      "they stopped explaining themselves to people who didn't deserve it",
      "they built a life that asked a lot of them",
      "they had a moment of genuine peace",
      "they became someone's safe person",
      "they did something you always hoped they would",
      "they called on a day that wasn't a holiday just to hear your voice",
      "they passed on something you gave them without knowing where it came from",
      "they started telling their own childhood stories",
      "they let themselves be helped",
      "they got through something alone and it was enough",
      "they made a choice you would have made",
      "they made a choice you wouldn't have, and it worked",
      "they learned to ask for what they need",
      "they sat with someone else's grief and didn't try to fix it",
      "they understood something about you they couldn't have before",
      "they started to understand why you were the way you were, and forgave it",
      "they had a dream about their childhood",
      "they realized they were okay",
      "they became someone's parent and understood everything differently",
      "they thought of something you said, at exactly the right moment",
    ],
  },
];

function sampleFragments(age: number, count = 4): string[] {
  const pool =
    FRAGMENTS_BY_AGE.find((b) => age <= b.maxAge)?.lines ??
    FRAGMENTS_BY_AGE[FRAGMENTS_BY_AGE.length - 1].lines;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

interface Props {
  childName: string;
  age?: number;
  gameId?: string | null;
  /** Live-streamed text from the LLM — shown over the fragment while generating. */
  streamingText?: string;
}

export function ProcessingScreen({ childName, age = 6, gameId, streamingText }: Props) {
  const [fragments] = useState(() => sampleFragments(age, 4 + Math.floor(Math.random() * 4)));
  const [fragmentIdx, setFragmentIdx] = useState(0);

  useEffect(() => {
    setFragmentIdx(0);
    const id = setInterval(() => {
      setFragmentIdx((i) => (i + 1) % fragments.length);
    }, 8000);
    return () => clearInterval(id);
  }, [fragments.length]);

  return (
    <div className="processing-screen">
      <div className="processing-figure">
        <ChildPortrait age={age} size={140} gameId={gameId} />
      </div>
      <p className="processing-name">{childName}</p>
      <div className="processing-fragment-area">
        {streamingText ? (
          <div className="processing-stream-text">{streamingText}</div>
        ) : (
          <span key={fragmentIdx} className="processing-fragment-text">
            {fragments[fragmentIdx]}
          </span>
        )}
      </div>
    </div>
  );
}
